import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";

export default function Home() {
  return (
    // fragment -envolve as teags que contem o conteudo do site
    <>
      <Head>
        <title>Fundamento do react</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World! Meu primeiro site em react</h1>
        <hr />
        <Welcome />
        <User />
        <hr /><br />
        <Description
          city="Pariquera-açu"
          age={18}
          email="marceloyogo37@gmail.com"
        />
        <br />
        <Pet name="Noah" breed="Netherland Dwarf" age={3} />
      </main>
    </>
  );
}
